### ISSUE TITLE
Connect pexip sdk android to vpn network?

### ISSUE THREAD

**Issue by trungkien221995** [pexip/pexkit-sdk#17]
I try connect pexip to VPN use OpenVPNConnect app. But when login conference my app crash.
Error:

 `02-01 11:52:45.258 5176-5404/com.android.vpcp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                Process: com.android.vpcp, PID: 5176
                                                                java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                    at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                 Caused by: com.spotify.dns.DnsException: Lookup of '_pexapp._tcp.pexipdemo.com' failed with code: 2 - timed out 
                                                                    at com.spotify.dns.XBillDnsSrvResolver.resolve(XBillDnsSrvResolver.java:59)
                                                                    at com.spotify.dns.RetainingDnsSrvResolver.resolve(RetainingDnsSrvResolver.java:46)
                                                                    at com.pexip.pexkit.SrvTask.doInBackground(SrvTask.java:43)
                                                                    at com.pexip.pexkit.SrvTask.doInBackground(SrvTask.java:19)
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                    at java.lang.Thread.run(Thread.java:818) 
`

**Comment by wuurrd** [comment]
This stack trace looks like the SRV lookup is failing for pexipdemo.com (which it shouldn't be) - can you verify that dns records are being correctly responded to through the VPN?
